# Generated by Django 6.1.1 on 2026-09-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='کپشن')),
                ('image', models.ImageField(upload_to='product/', verbose_name='عکس')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('discount_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
